# Build settings
theme: jekyll-theme-chirpy

lang : en
plugins:
  - jekyll-feed
  - jekyll-compose
#Timezone
timezone: Asia/Tokyo

# SEO Shit
title: DogJam
tagline : A retirement crew for gamers 
description: >- # this means to ignore newlines until "baseurl:"
  dogJam is a retirement home for veterans that still play a fair amount of GW but would like a more relaxed atmosphere. 
  We do top 300 in prelims then after that, aim to secure top 2500 in crew totals.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dogjam.site" # the base hostname & protocol for your site, e.g. http://example.com


github:
  username: yuchaaa

twitter:
  username: 95rn16 
social: 
  name : DogJam
  email: me@kskm.org
  links:
  - https://twitter.com/uyupekochan

theme_mode : dark
toc: true 

avatar: "https://media.discordapp.net/attachments/1182602381746241566/1254044718090817567/IMG_20240622_084705.png?ex=66e57c27&is=66e42aa7&hm=b8e4e41155ca7966d28decc79c445c40444ce91f7f19a95402ca71cd71ac6675&=&format=webp&quality=lossless"

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed
paginate : 10
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/